trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
#Test Stage
- stage: Test
  displayName: Run Unit Tests
  jobs:
  - job: RunTests
    displayName: Run Tests
    pool:
      vmImage: defaul
    steps:
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.x.x'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - script: dotnet restore
      displayName: Restore NuGet packages

    - script: dotnet build --no-restore
      displayName: Build solution

    - script: dotnet test BookStore.Test/BookStore.Test.csproj --no-build --verbosity normal
      displayName: Run unit tests from BookStore.Test project

- stage: Build
  displayName: Build image
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: default
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/BookStore.API/Dockerfile'
        tags: |
          $(tag)
